// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxhK1WtJMGO76kGwJvDoe2Y5kMHnzzNWI',
    appId: '1:169808652911:web:02b13a70a6cc2e9256fb9a',
    messagingSenderId: '169808652911',
    projectId: 'jeleappstest-8201d',
    authDomain: 'jeleappstest-8201d.firebaseapp.com',
    storageBucket: 'jeleappstest-8201d.firebasestorage.app',
    measurementId: 'G-93NTNNLTKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd2AS2XZrRCmGbvIAMGlco2YyibzTiiZA',
    appId: '1:169808652911:android:79d89d07d63634f556fb9a',
    messagingSenderId: '169808652911',
    projectId: 'jeleappstest-8201d',
    storageBucket: 'jeleappstest-8201d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuQ2QlmSoGPbYlRhISYeOk_9HEvXFuc7U',
    appId: '1:169808652911:ios:e0f5f5bb5e94cd2656fb9a',
    messagingSenderId: '169808652911',
    projectId: 'jeleappstest-8201d',
    storageBucket: 'jeleappstest-8201d.firebasestorage.app',
    iosBundleId: 'com.example.vpnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu6ZldRspcXQbmg8YNOMZHteW1FrnPfFk',
    appId: '1:169808652911:web:11c75858c1295f8556fb9a',
    messagingSenderId: '169808652911',
    projectId: 'jeleappstest-8201d',
    authDomain: 'jeleappstest-8201d.firebaseapp.com',
    storageBucket: 'jeleappstest-8201d.firebasestorage.app',
    measurementId: 'G-KJQ5HJS4XG',
  );
}
